### ISSUE TITLE
English Version?

### ISSUE THREAD

**Issue by FlyJam** [code-mcx/mcx-dialog-mobile#2]
Hi, is there an English version?

**Comment by code-mcx** [comment]
Hello @FlyJam , not provided english version.

**Comment by code-mcx** [comment]
Hello @FlyJam , the english version had published. Your can see the english [demo](https://github.com/code-mcx/mcx-dialog-mobile/blob/master/index.html), and [more configurable optoins](https://github.com/code-mcx/mcx-dialog-mobile/releases/tag/v0.2.0).
