### ISSUE TITLE
src option in loading 

### ISSUE THREAD

**Issue by Ykeng** [code-mcx/mcx-dialog-mobile#5]
##### looking your code, the src option is never be used.

![image](https://user-images.githubusercontent.com/13504029/50726103-53ec8000-1143-11e9-9488-22f198912c49.png)

**Comment by code-mcx** [comment]
Hello @Ykeng , this option is used in browser environment. When using `script` tag, it is  useful.

**Comment by Ykeng** [comment]
thanks for youra reply.

i mean Loading is always useful when set src option to any string. 
example blow may help.

**this is example in index.html and works fine**
```
mcxDialog.loading({
      src: "dist/img",
      hint: "加载中..."  //指定提示内容
});
```

**i change the "src" option  and the example also works fine**
```

mcxDialog.loading({
      src: "dist/img/directory/not/exist",
      hint: "加载中..."  //指定提示内容
});
```

**Comment by code-mcx** [comment]
This option is not valid in the npm environment.

```html
<script type="text/javascript" src="dist/mcx-dialog.js"></script>
```
```javascript
mcxDialog.loading({
      src: "dist/img/directory/not/exist",
      hint: "加载中..."  //指定提示内容
});
```
Then will get status of 404.

**Comment by Ykeng** [comment]
thanks for your time
